### ISSUE TITLE
添加课程资料

### ISSUE THREAD

**Issue by YDX-2147483647** [flwfdd/BIT101#1]
[BITNP/SecretWeapon](https://github.com/BITNP/SecretWeapon) 有不少课程资料可上传到 [BIT101 Drive](https://onedrive.bit101.cn/zh-CN/)。

**Comment by flwfdd** [comment]
好的（但是感觉大部分都还是有些许过时了

**Comment by YDX-2147483647** [comment]
是，只有个别是新的。

- [大学物理 · 活页练习_习题映射表.md](https://github.com/BITNP/SecretWeapon/blob/master/ElectronicEngineering/大学物理/活页练习_习题映射表.md)
- [学术用途英语 · 听力原文等](https://github.com/BITNP/SecretWeapon/tree/master/ElectronicEngineering/学术用途英语)

不过 OneDrive 的容量宽裕吗？

**Comment by flwfdd** [comment]
OneDrive 只有区区5T（逃
不过不是正规账号，之后可能需要自己做容灾备份。

**Comment by YDX-2147483647** [comment]
啊，那我把这儿关了吧……

**Comment by cxw620** [comment]
> OneDrive 只有区区5T（逃 不过不是正规账号，之后可能需要自己做容灾备份。
tb的世纪互联带API权限的绝对不稳定, 1年跑路吧(这儿有个例子). 
可以整个OneDrive开发者订阅, 5T*25, 不滥用基本没问题, 就是国际版有点慢. 虽然如果走Cloudflare Worker代理, 校园网IPv6可以跑满速度.
P.S. 正规OneDrive世纪互联2T每年需要RMB 354, 5T每年需要RMB 700+, 但购买5份订阅可升级25T, *5就是125T. 如果找到人拼团也是极好的
