### ISSUE TITLE
部分教学大纲的文件名后缀错误

### ISSUE THREAD

**Issue by FrzMtrsprt** [flwfdd/BIT101#10]
[计算方法-100063126](https://onedrive.bit101.cn/zh-CN/%E6%95%99%E5%AD%A6%E5%A4%A7%E7%BA%B2/%E8%AE%A1%E7%AE%97%E6%96%B9%E6%B3%95-100063126.doc)的教学大纲是pdf格式，但文件名后缀却是doc，是不是批量重命名时出了问题呢？

**Comment by flwfdd** [comment]
雀食，，，一股脑改成`.doc`了....之前下了好多都没见过`.pdf`....感谢提醒qwq

**Comment by FrzMtrsprt** [comment]
Emm这个文件是不是又变成pdf了

**Comment by flwfdd** [comment]
我能说是一直没改吗、、、
在982facd8b24ae819bba80f75e6d4bf56eb6a3407进行了修改 现在大概是可以了

**Comment by flwfdd** [comment]
我能说是一直没改吗、、、
在 982facd8b24ae819bba80f75e6d4bf56eb6a3407 进行了修改 现在大概是可以了
