### ISSUE TITLE
[Bug] 部分课程重复

### ISSUE THREAD

**Issue by FrzMtrsprt** [flwfdd/BIT101#16]
如图所示，搜索结果中有三个名为机器学习基础的课程，且课程编号均为100064166。
![image](https://github.com/flwfdd/BIT101/assets/15852717/20fafb27-f3d2-4db3-82c3-8e00dce348e6)

**Comment by flwfdd** [comment]
非Bug，是Feature。
基于基本校情考虑，同一门课程不同老师间的差别往往很大，故合并是不合适的。图中这样情况的原因应该是至少分别有三个学期由不同老师组合任教。

**Comment by FrzMtrsprt** [comment]
明白了，谢谢
