### ISSUE TITLE
成绩查询功能不能正确计算含缓考和挂科的情况

### ISSUE THREAD

**Issue by AndyBlocker** [flwfdd/BIT101#4]
成绩查询中会将含上述情况的课程作为一般课程计算，与学校成绩计算方式有出入

**Comment by flwfdd** [comment]
那请问缓考和挂科的在查询时能看出区别吗？（例如成绩详情中有标注吗）
以及正确的算法应该是怎样的呢？
（我确实还暂且没有过这样的经历，没有样例😂

**Comment by AndyBlocker** [comment]
系统里面"成绩标识"默认是空的，标注缓考/缺考的时候代表当次考试出现了这些情况，重新考试前这一栏成绩会被记为0，重考后会把重考成绩补充到这一栏里，不产生一行新成绩（例外是原课程取消出现课程替代的情况，原考试会一直标记缓考0分但还会生成一行新课程成绩，这门课的“成绩标识”为空，“考试性质”为重考）。
考试挂科不会有特殊标记，按照学校保研成绩计算的规定挂科应该是平均分中记0分；参加补考/重考/重修的考试“考试性质”会有对应的标识，同时“是否第一次考试”标识是否。

学校自己算保研均分和出示成绩单上面又有点区别，这些弄起来感觉挺麻烦的。如果图省事的话最简单的办法应该是计算平均分的时候相同课程编号或者课程名称的课程只算最新一次（最靠后的表项）的成绩。按照学校保研成绩计算的方式应该就是只统计“是否第一次考试”为是（对应一般课程和能够正常缓考的课程）的考试成绩，成绩低于60的按0分计，至于缓考而出现课程替代的情况的干脆再加一个手动筛选的list让用户能够自己勾选或者反选需要计算的成绩，一了百了的解决了学校可能弄出来的各种神秘操作😂

**Comment by YDX-2147483647** [comment]
相关：[可信电子成绩单申请](https://jwc.bit.edu.cn/cjd)（[校外](https://webvpn.bit.edu.cn/https/77726476706e69737468656265737421fae042d225397c1e7b0c9ce29b5b/cjd)）、[学分绩点计算](https://jwc.bit.edu.cn/jwyx/cjgl/fe90fb3818184909bfc9228aada43970.htm)。

**Comment by flwfdd** [comment]
麻了 堪比规则类怪谈（雾
不如我就先直接加一个自动返回可信成绩单预览图片的功能得了hhh

**Comment by AndyBlocker** [comment]
> 麻了 堪比规则类怪谈（雾
> 不如我就先直接加一个自动返回可信成绩单预览图片的功能得了hhh

只统计同名课程的最近成绩应该实现起来最简单😂

**Comment by flwfdd** [comment]
已经添加了手动选择课程是否计入GPA的功能，并且应该会自动不选那些重修和0分的科目，我没有可供测试的账号，麻烦试试看？
另外也支持可信成绩查询了。
如果还有任何问题也请反馈awa

**Comment by AndyBlocker** [comment]
OK了👍
