### ISSUE TITLE
评论过长会挤长宽度

### ISSUE THREAD

**Issue by YDX-2147483647** [flwfdd/BIT101#5]
![](https://user-images.githubusercontent.com/73375426/185277807-521c4561-65f4-4bd6-84e5-5db1a7d4e6c6.png)

如图，这种问题只会在连续大量“字母”（如 URL）时出现。

似乎把[`word-break`](https://developer.mozilla.org/en-US/docs/Web/CSS/word-break)设置成`break-all`能修复。

**Comment by flwfdd** [comment]
fixed
