### ISSUE TITLE
一个潜在的前端XSS注入漏洞

### ISSUE THREAD

**Issue by BobH233** [flwfdd/BIT101#6]
# 实例

[文章链接](https://bit101.cn/#/paper/show/13)
点开后，图片加载完会加载js脚本，弹出alert

# 原因

对于文章的内容url转义，仅仅在前端转换后放心交给后端是万万不可的。
后端不能对前端数据充分信任，这个注入就是使用postman手动替换了html转义&lt;&gt;，导致注入js脚本

# 影响

以用户的身份发表文章，内容包含自己的cookie，绕过HttpOnly限制
造成账号权限泄漏

# 修改意见

1. html转义放置在python后端执行

2. 前端对标签内容赋值时使用innerText而不是InnerHTML，避免注入html标签的可能性。

# 求大佬给个qq好友位，可以交流交流

特立2021级的（

**Comment by YDX-2147483647** [comment]
// [关于页](https://bit101.cn/#/about/)有QQ交流群。
