### ISSUE TITLE
学长，网站貌似上不去了...

### ISSUE THREAD

**Issue by Oldmemory1** [flwfdd/BIT101#8]
今天打开的时候会404...（不知道是不是我这里的问题）
图在这：
![20221110224321](https://user-images.githubusercontent.com/94025104/201121635-b410b36a-b27f-4a81-af0a-1036f0f5dda7.png)

**Comment by Oldmemory1** [comment]
bit101.cn能正常访问
但是那个onedrive的界面不知道为啥访问不了了。。。

**Comment by flwfdd** [comment]
前几天该OneDrive账号被运营商世纪互联封禁，文件都在的，我这周末考完试会尝试解决

**Comment by flwfdd** [comment]
（另外我大概不是学长....

**Comment by flwfdd** [comment]
已经修复 换上新的号了 但不是世纪互联了
